# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title : oemof tutorials
author: Eva Schischke
logo: figures/logo_oemof_mid.svg
email: eva.schischke@umsicht.fraunhofer.de

# Short description about the book
description: >-
  Tutorials for packages within the oemof community

execute:
  execute_notebooks           : cache
  timeout                     : 300

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "figures/logo_oemof_small.svg"
  home_page_in_navbar: false

# Information about where the book exists on the web
repository:
  url: https://github.com/oemof/oemof-tutorials  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

